-- AlterTable
ALTER TABLE "scores" ALTER COLUMN "points" DROP DEFAULT,
ALTER COLUMN "points" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "kills" DROP DEFAULT,
ALTER COLUMN "deaths" DROP DEFAULT,
ALTER COLUMN "assists" DROP DEFAULT;
